### ISSUE TITLE
 Failed at the getting-started@1.0.0 bootstrapAssets script 'node cli.js landregistry bootstrap'.

### ISSUE THREAD

**Issue by andreevym** [hyperledger/composer-sample-applications#20]
```Command failed.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! getting-started@1.0.0 bootstrapAssets: `node cli.js landregistry bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the getting-started@1.0.0 bootstrapAssets script 'node cli.js landregistry bootstrap'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the getting-started package,
npm ERR! not with npm itself.
npm ERR! **Tell the author that this fails on your system**:
npm ERR!     node cli.js landregistry bootstrap
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs getting-started
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls getting-started
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2017-04-06T11_30_18_972Z-debug.log
npm ERR! Test failed.  See above for more details.
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'bootstrapAssets' ]
2 info using npm@4.4.4
3 info using node@v6.8.1
4 verbose run-script [ 'prebootstrapAssets',
4 verbose run-script   'bootstrapAssets',
4 verbose run-script   'postbootstrapAssets' ]
5 info lifecycle getting-started@1.0.0~prebootstrapAssets: getting-started@1.0.0
6 silly lifecycle getting-started@1.0.0~prebootstrapAssets: no script for prebootstrapAssets, continuing
7 info lifecycle getting-started@1.0.0~bootstrapAssets: getting-started@1.0.0
8 verbose lifecycle getting-started@1.0.0~bootstrapAssets: unsafe-perm in lifecycle true
9 verbose lifecycle getting-started@1.0.0~bootstrapAssets: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/yuryandreev/projects/sample-applications/packages/getting-started/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/yuryandreev/projects/sample-applications/packages/getting-started/node_modules/.bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/opt/local/bin:/opt/local/sbin::/Library/gradle-3.0/bin:/Users/yuryandreev/Documents/development/go_home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin
10 verbose lifecycle getting-started@1.0.0~bootstrapAssets: CWD: /Users/yuryandreev/projects/sample-applications/packages/getting-started
11 silly lifecycle getting-started@1.0.0~bootstrapAssets: Args: [ '-c', 'node cli.js landregistry bootstrap' ]
12 silly lifecycle getting-started@1.0.0~bootstrapAssets: Returned: code: 1  signal: null
13 info lifecycle getting-started@1.0.0~bootstrapAssets: Failed to exec bootstrapAssets script
14 verbose stack Error: getting-started@1.0.0 bootstrapAssets: `node cli.js landregistry bootstrap`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid getting-started@1.0.0
16 verbose cwd /Users/yuryandreev/projects/sample-applications/packages/getting-started
17 verbose Darwin 16.4.0
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "bootstrapAssets"
19 verbose node v6.8.1
20 verbose npm  v4.4.4
21 error code ELIFECYCLE
22 error errno 1
23 error getting-started@1.0.0 bootstrapAssets: `node cli.js landregistry bootstrap`
23 error Exit status 1
24 error Failed at the getting-started@1.0.0 bootstrapAssets script 'node cli.js landregistry bootstrap'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the getting-started package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     node cli.js landregistry bootstrap
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs getting-started
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls getting-started
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by mbwhite** [comment]
@andreevym could you summarise the steps you did to get to this point please...

**Comment by jvkatzman** [comment]
I am having the same issue, and I was following the tutorial.  I am using a mac

**Comment by davidkel** [comment]
I can't recreate this. If you still have a problem, please could you open a new issue rather than re-opening this one. A lot has changed in this repo now so the information here isn't relevant anymore.

**Comment by jvkatzman** [comment]
Thanks. This was a long time ago and I've moved on.


-----Original Message-----
