### ISSUE TITLE
failed on the step of "npm run deployNetwork"

### ISSUE THREAD

**Issue by WillZhuang** [hyperledger/composer-sample-applications#47]
Thank you very much for you open source contribution!
I am following the steps of [https://github.com/hyperledger/composer-sample-applications/blob/master/packages/digitalproperty-app/README.md](https://github.com/hyperledger/composer-sample-applications/blob/master/packages/digitalproperty-app/README.md),
everything goes well, but the last step "npm run deployNetwork", the log is as below.

Could you kindly help to check and review?

```
root@will-virtual-machine:~/github/composer-sample-applications/packages/getting-started# npm run deployNetwork

> getting-started@0.0.1 deployNetwork /root/github/composer-sample-applications/packages/getting-started
> composer archive create --sourceName digitalproperty-network --sourceType module --archiveFile digitalPropertyNetwork.bna && composer network deploy --archiveFile digitalPropertyNetwork.bna  --enrollId WebAppAdmin --enrollSecret DJY27pEnl16d && composer network list -n digitalproperty-network --enrollId WebAppAdmin --enrollSecret DJY27pEnl16d


Creating Business Network Archive

Not found in main node_module search path, trying current directory
	Current Directory: /root/github/composer-sample-applications/packages/getting-started/node_modules/digitalproperty-network

Looking for package.json of Business Network Definition
	Input directory: /root/github/composer-sample-applications/packages/getting-started/node_modules/digitalproperty-network

Found:
	Description: Digital Property Network
	Name: digitalproperty-network
	Identifier: digitalproperty-network@0.0.9

Written Business Network Definition Archive file to 
	Output file: digitalPropertyNetwork.bna

Command succeeded


Deploying business network from archive: digitalPropertyNetwork.bna
Business network definition:
	Identifier: digitalproperty-network@0.0.9
	Description: Digital Property Network

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: event message must be properly signed by an identity from the same organization as the peer: [failed deserializing event creator: [Expected MSP ID Org1MSP, received ]]
    at ClientDuplexStream._emitStatusIfDone (/usr/lib/node_modules/composer-cli/node_modules/grpc/src/node/src/client.js:189:19)
    at ClientDuplexStream._receiveStatus (/usr/lib/node_modules/composer-cli/node_modules/grpc/src/node/src/client.js:169:8)
    at /usr/lib/node_modules/composer-cli/node_modules/grpc/src/node/src/client.js:634:14

npm ERR! Linux 4.8.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "deployNetwork"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! getting-started@0.0.1 deployNetwork: `composer archive create --sourceName digitalproperty-network --sourceType module --archiveFile digitalPropertyNetwork.bna && composer network deploy --archiveFile digitalPropertyNetwork.bna  --enrollId WebAppAdmin --enrollSecret DJY27pEnl16d && composer network list -n digitalproperty-network --enrollId WebAppAdmin --enrollSecret DJY27pEnl16d`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the getting-started@0.0.1 deployNetwork script 'composer archive create --sourceName digitalproperty-network --sourceType module --archiveFile digitalPropertyNetwork.bna && composer network deploy --archiveFile digitalPropertyNetwork.bna  --enrollId WebAppAdmin --enrollSecret DJY27pEnl16d && composer network list -n digitalproperty-network --enrollId WebAppAdmin --enrollSecret DJY27pEnl16d'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the getting-started package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     composer archive create --sourceName digitalproperty-network --sourceType module --archiveFile digitalPropertyNetwork.bna && composer network deploy --archiveFile digitalPropertyNetwork.bna  --enrollId WebAppAdmin --enrollSecret DJY27pEnl16d && composer network list -n digitalproperty-network --enrollId WebAppAdmin --enrollSecret DJY27pEnl16d
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs getting-started
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls getting-started
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/github/composer-sample-applications/packages/getting-started/npm-debug.log

```

**Comment by mbwhite** [comment]
The issue here is that the version of the node modules that are being used in composer are at mismatched levels...  The backend Fabric is at the latest v1.0 beta level, but your composer is (I'm guessing at 0.7.5).

It is worth updating the node modules and make sure they are at 0.8.0 (released yesterday).

If you have other issues getting started please head to our Rocket-Chat channel. https://chat.hyperledger.org/channel/composer

**Comment by WillZhuang** [comment]
Thank you
